"""empty message

Revision ID: 1f7060271e76
Revises: 72bcbccff5a8
Create Date: 2019-10-03 15:41:50.025987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7060271e76'
down_revision = '72bcbccff5a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('img_url', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('reviewby', sa.String(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('excercises', sa.Column('week', sa.Integer(), nullable=True))
    op.add_column('lifestyles', sa.Column('week', sa.Integer(), nullable=True))
    op.add_column('losses', sa.Column('week', sa.Integer(), nullable=True))
    op.add_column('symtoms', sa.Column('week', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symtoms', 'week')
    op.drop_column('losses', 'week')
    op.drop_column('lifestyles', 'week')
    op.drop_column('excercises', 'week')
    op.drop_table('nutrition')
    # ### end Alembic commands ###
