"""empty message

Revision ID: 25451b4f9c2f
Revises: f0cd9d2e076c
Create Date: 2019-09-26 12:02:50.609284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25451b4f9c2f'
down_revision = 'f0cd9d2e076c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_column('user', 'email')
    op.drop_column('user', 'password')
    op.drop_column('user', 'duedate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('duedate', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    # ### end Alembic commands ###
