"""empty message

Revision ID: 56095ff04924
Revises: 0eef0cad245f
Create Date: 2019-10-02 13:11:57.773342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56095ff04924'
down_revision = '0eef0cad245f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('cover_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'cover_url')
    # ### end Alembic commands ###
