"""empty message

Revision ID: 5bf88277c9e6
Revises: 82c021470fc0
Create Date: 2019-09-30 13:49:32.341936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf88277c9e6'
down_revision = '82c021470fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'date_conception')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('date_conception', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
