"""empty message

Revision ID: 72bcbccff5a8
Revises: ae9ba26ac63d
Create Date: 2019-10-03 08:53:45.084781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72bcbccff5a8'
down_revision = 'ae9ba26ac63d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nutrition', 'intro',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nutrition', 'intro',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
