"""empty message

Revision ID: 885283b1816e
Revises: 5bf88277c9e6
Create Date: 2019-09-30 16:28:02.930928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885283b1816e'
down_revision = '5bf88277c9e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('profile_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'profile_url')
    # ### end Alembic commands ###
