"""empty message

Revision ID: 937274f9581c
Revises: 7483154411be
Create Date: 2019-10-01 09:32:34.554717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937274f9581c'
down_revision = '7483154411be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
