"""empty message

Revision ID: 9c67306c83f3
Revises: a940b60f0ac0
Create Date: 2019-09-26 12:32:09.594919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c67306c83f3'
down_revision = 'a940b60f0ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'duedate')
    op.drop_column('user', 'email')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('duedate', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
