"""empty message

Revision ID: b12a7d8aefd5
Revises: 897cfc933212
Create Date: 2019-09-30 17:07:32.085409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12a7d8aefd5'
down_revision = '897cfc933212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'profile', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_column('profile', 'user_id')
    # ### end Alembic commands ###
