"""empty message

Revision ID: dceeae470e27
Revises: 12463e1e1308
Create Date: 2019-09-30 17:31:21.670362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dceeae470e27'
down_revision = '12463e1e1308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'flask_dance_oauth', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'profile', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'token', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_constraint(None, 'flask_dance_oauth', type_='foreignkey')
    # ### end Alembic commands ###
